### ISSUE TITLE
Recent update (0.4.0?) broke letsencrypt renewal, with "CertStorageError: expected /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/cert.pem to be a symlink"

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1003]
My gateway is currently stuck with an expired Let's Encrypt cert (expired May 7) and it's unable to get a new one. This renders its web portal unusable in Firefox for Android (which AFAICT does not expose a way for users to click through its expired-cert SSL error page).

My gateway started at version 0.3.0 when I originally set it up, and (after receiving OTA updates) it's currently at version 0.4.0, which it received on April 18th. I'm guessing it's been unable to get a new cert since that update.

I suspect this has to do with the "Everything now lives in ~/.mozilla-iot" change [listed in the 0.4.0 release notes](https://github.com/mozilla-iot/gateway/releases/tag/0.4.0). CC @dhylands

**Comment by dholbert** [comment]
The file `/home/pi/.mozilla-iot/var/log/letsencrypt.log` has the following contents:
````2018-05-12 00:00:52,135:DEBUG:certbot.main:Root logging level set at 20
2018-05-12 00:00:52,139:INFO:certbot.main:Saving debug log to /home/pi/.mozilla-iot/var/log/letsencrypt.log
2018-05-12 00:00:52,143:DEBUG:certbot.main:certbot version: 0.10.2
2018-05-12 00:00:52,144:DEBUG:certbot.main:Arguments: ['--config-dir', '/home/pi/.mozilla-iot/etc', '--logs-dir', '/home/pi/.mozilla-iot/var/log', '--work-dir', '/home/pi/.mozilla-iot/var/lib', '--renew-hook', '/home/pi/mozilla-iot/gateway/tools/deploy-certificates.sh']
2018-05-12 00:00:52,148:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2018-05-12 00:00:52,163:WARNING:certbot.renewal:expected /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/cert.pem to be a symlink
2018-05-12 00:00:52,164:WARNING:certbot.renewal:Renewal configuration file /home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf is broken. Skipping.
2018-05-12 00:00:52,167:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 59, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python2.7/dist-packages/certbot/storage.py", line 392, in __init__
    self._check_symlinks()
  File "/usr/lib/python2.7/dist-packages/certbot/storage.py", line 431, in _check_symlinks
    "expected {0} to be a symlink".format(link))
CertStorageError: expected /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/cert.pem to be a symlink

2018-05-12 00:00:52,169:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 655, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 0 renew failure(s), 1 parse failure(s)
````

Note that it's looking at "...pi/mozilla-iot/" there -- the "." is missing in the path. Indeed, in the conf file referenced in the log above, it seems there are no dots in the mozilla-iot directory entries. So after the dot-directory-migration noted in the release notes, we've got stale directories left in this conf file, it seems.

**Comment by dholbert** [comment]
Here's the contents of the conf file `/home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf` -- note the missing `.` before `mozilla-iot` in its directory entries:
````

#cert = :configDir/live/:hostname/cert.pem
cert = /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/cert.pem
privkey = /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/privkey.pem
chain = /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/chain.pem
fullchain = /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/fullchain.pem

# Options and defaults used in the renewal process
[renewalparams]
no_self_upgrade = True
apache_enmod = a2enmod
no_verify_ssl = False
ifaces = None
apache_dismod = a2dismod
register_unsafely_without_email = False
apache_handle_modules = True
uir = None
installer = None
nginx_ctl = nginx
config_dir = /home/pi/mozilla-iot/etc
text_mode = True
# junk?
# https://github.com/letsencrypt/letsencrypt/issues/1955
func = <function obtain_cert at 0x7f093a163c08>
staging = False
prepare = False
work_dir = /home/pi/mozilla-iot/var/lib
tos = True
init = False
http01_port = None
duplicate = False
noninteractive_mode = True
# this is for the domain
key_path = /home/pi/mozilla-iot/etc/live/eagle.mozilla-iot.org/privkey.pem
nginx = False
nginx_server_root = /etc/nginx
fullchain_path = :fullchain_path
email = certificate@mozilla-iot.org
csr = None
agree_dev_preview = None
redirect = None
verb = certonly
verbose_count = -3
config_file = None
renew_by_default = True
hsts = False
apache_handle_sites = True
authenticator = webroot
domains = eagle.mozilla-iot.org, #comma,delimited,list
rsa_key_size = 2048
apache_challenge_location = /etc/apache2
# starts at 0 and increments at every renewal
checkpoints = 0
manual_test_mode = False
apache = False
cert_path = :cert_path
webroot_path = /home/pi/mozilla-iot/gateway/static, # comma,delimited,list
reinstall = False
expand = False
strict_permissions = False
apache_server_root = /etc/apache2
# https://github.com/letsencrypt/letsencrypt/issues/1948
account = 48bd2479ee653f423d40723bb6eed5ec
dry_run = False
manual_public_ip_logging_ok = False
chain_path = :chain_path
break_my_certs = False
standalone = False
manual = False
server = https://acme-v01.api.letsencrypt.org/directory
standalone_supported_challenges = "http-01,tls-sni-01"
webroot = True
os_packages_only = False
apache_init_script = None
user_agent = None
apache_le_vhost_ext = -le-ssl.conf
debug = False
tls_sni_01_port = 443
logs_dir = /home/pi/mozilla-iot/var/log
apache_vhost_root = /etc/apache2/sites-available
configurator = None
must_staple = True
[[webroot_map]]
# :hostname = :webroot_path
eagle.mozilla-iot.org = /home/pi/mozilla-iot/gateway/static
````
