### ISSUE TITLE
Error while building through yarn

### ISSUE THREAD

**Issue by karthikveeramani** [mozilla-iot/gateway#1226]
After I pull the code on Windows 10 and run yarn, I see the following error. Could someone help? I know at least one more person who have done this successfully with VS 2017 and I have the same version.

```
(mozillaenv) C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi )  else (node "" build --fallback-to-build --module=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Computer\\Desktop\\User\\MozillaIot\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Computer\\Desktop\\User\\MozillaIot\\node_modules\\sqlite3\\lib\\binding\\node-v57-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Computer\Desktop\User\MozillaIot\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Computer\\Desktop\\User\\MozillaIot\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Computer\Desktop\User\MozillaIot\node_modules\sqlite3\lib\binding\node-v57-win32-x64 --napi_version=3 --node_abi_napi=napi' (
```

**Comment by sogaani** [comment]
hi @karthikveeramani 
It seems to use incompatible version of MSBuild tools.
We should install MSBuild tools for VS2015 and configurations to build native modules on windows. 
[This document](https://github.com/nodejs/node-gyp#on-windows) is helpful to install them.

Easiest option is below.

> Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).

**Comment by rzr** [comment]
Is it specific to windows ? if yes please relabel the issue

**Comment by mrstegeman** [comment]
@karthikveeramani Is this still an issue?

**Comment by karthikveeramani** [comment]
Yes it was the last I tried, but I abandoned the idea of building this on Windows as it was rather complicated and didn't have enough instructions to get through.

**Comment by rzr** [comment]
may docker comes to rescue ?

**Comment by mrstegeman** [comment]
Closing, as we no longer use yarn.

**Comment by rzr** [comment]
Alternatively WLS can come to rescue It worked for me when I tried on webthing-iotjs , I think gateway worked too, some hints at:

https://github.com/rzr/webthing-iotjs/wiki
