### ISSUE TITLE
Actual test failure: thingColorDisplayed

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1338]
```
Summary of all failing tests
 FAIL  src/test/browser/things-view/thing-test.js (50.742s)
  ● Thing › should render an onOffColorLight and be able to change properties
    TypeError: Cannot read property 'match' of undefined
      
      at ThingSection.thingColorDisplayed (src/test/browser/page-object/things-page.js:76:84)
          at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  ● Thing › should render a dimmableColorLight and be able to change properties
    TypeError: Cannot read property 'match' of undefined
      
      at ThingSection.thingColorDisplayed (src/test/browser/page-object/things-page.js:76:84)
          at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Notably this only fails on travis and works locally.

**Comment by mrstegeman** [comment]
Wonder if it has something to do with the new Firefox release yesterday?

**Comment by hobinjk** [comment]
It looks like the 'webthing-light-capability > div > div > svg' selector only works if the shadow DOM is a polyfill and not a real implementation. I should be able to fix this and any similar issues
