### ISSUE TITLE
Error while getting ready to start. (npm start --check-wifi)

### ISSUE THREAD

**Issue by LuBlaBo** [mozilla-iot/gateway#1351]
Hello there,

i have a problem with your prebuild version of the gateway. I run into an error while running "run-app.sh" or npm start. (Same error at both)

Below is a snippet of my errormessage:
npm start -- --check-wifi

> things-gateway@0.5.1 start /home/pi/mozilla-iot/gateway
> webpack && node build/gateway.js "--check-wifi"

/home/pi/mozilla-iot/gateway/node_modules/webpack/lib/Module.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at NativeCompileCache._moduleCompile (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/webpack/lib/NormalModule.js:20:16)
    at Module._compile (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/webpack/lib/NormalModuleFactory.js:16:22)
    at Module._compile (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/webpack/lib/Compiler.js:22:29)
    at Module._compile (/home/pi/mozilla-iot/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! things-gateway@0.5.1 start: `webpack && node build/gateway.js "--check-wifi"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the things-gateway@0.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can some one tell me what i am doing wrong? (Tryed with npm install and just got an error... :( )

Thank you for your help 

~Lukas

**Comment by hobinjk** [comment]
That looks like the error you get if `npm install` pulls in the wrong version of babel. If you install yarn by running `npm install -g yarn` then run `yarn` in the gateway directory it should install all the correct dependency versions and work as expected.

**Comment by LuBlaBo** [comment]
Hey @hobinjk ,

i have tried like you said. With a bunch of other error while running yarn in the gateway dir i want to start the gateway with npm start. That gaves me a "Permission denied" error. The same with the run-app.sh :/

Snippet from my console:

> things-gateway@0.5.1 start /home/pi/mozilla-iot/gateway
> webpack && node build/gateway.js "--check-wifi"

sh: 1: webpack: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! things-gateway@0.5.1 start: `webpack && node build/gateway.js "--check-wifi"`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the things-gateway@0.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Maybe i should download the prebuilded image and flash it again. At this time i think i have to say, that i want to run this on a Pi Zero W.

Thank you for your passion 👍

**Comment by dhylands** [comment]
The permission denied is most likely due to running some previous command using sudo and the files are owned by root.

**Comment by LuBlaBo** [comment]
I just re-flashed the provided image. Now it works 👍🏽

Seems like ghosts in the machine 😂

I will close this... Thank you all
