### ISSUE TITLE
gateway fails to start if there is no internet connection

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1401]
When I was in Hong Kong, I tried starting the gateway standalone, i.e. not connected to the internet.

It failed to start with the following error:
```
Opening database: /home/dhylands/moziot/.mozilla-iot/config/db.sqlite3
2018-10-02 19:16:32.947 HTTP server listening on port 8080
2018-10-02 19:16:32.988 Not checking SHA256SUMS file for zigbee-adapter since a .git directory was detected
2018-10-02 19:16:33.054 DNS config is: dave-work
2018-10-02 19:16:33.055 Service Discovery: changing profile - local domain is now: dave-work
2018-10-02 19:16:33.136 Service Discovery: state changed to: true
Error: send ENETUNREACH 224.0.0.251:5353
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:499:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! things-gateway@0.6.0 start: `webpack && node build/gateway.js "-d"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the things-gateway@0.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hobinjk** [comment]
From the IP address 224.0.0.251 this appears to be an issue with mDNS/dnssd

**Comment by dhylands** [comment]
That's the multicast IP address. I ran into this problem when trying to run the gateway on my laptop with no Wifi connection or ethernet connection, so there were no adapters present which supported multicast.

I think we just need to add a try/catch someplace and not make it crash.

I wasn;t able to run the gateway until I setup a hotspot on my phone and connected to that.

**Comment by jaller94** [comment]
The project `webthing-node` has the same issue.
mozilla-iot/webthing-node#70
