### ISSUE TITLE
certificate invalid / renewal configuration file invalid

### ISSUE THREAD

**Issue by cmatheson** [mozilla-iot/gateway#1403]
A few weeks ago my gateway stopped working from being accessible .mozilla-iot.org domain (I'm getting SSL errors).  The DNS record still points to my ip, and the gateway works fine locally (via gateway.lan).  I'm still getting updates (auto-updated to mozilla-iot 0.6 yesterday).  

I get this error when I run `~/mozilla-iot/gateway/tools/renew-certificates.sh`:

```
-------------------------------------------------------------------------------
Processing /home/pi/.mozilla-iot/etc/renewal/MYDOMAIN.mozilla-iot.org.conf
-------------------------------------------------------------------------------
[('PEM routines', 'PEM_read_bio', 'no start line')]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 260, in _load_cert_or_req
    return load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1661, in load_certificate
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
Renewal configuration file /home/pi/.mozilla-iot/etc/renewal/MYDOMAIN.mozilla-iot.org.conf produced an unexpected error: [('PEM routines', 'PEM_read_bio', 'no start line')]. Skipping.

No renewals were attempted.
No hooks were run.

Additionally, the following renewal configuration files were invalid:·
  /home/pi/.mozilla-iot/etc/renewal/MYDOMAIN.mozilla-iot.org.conf (parsefail)
```

How can I fix that mozilla-iot.org.conf file?  I should also note that all the .pem files in /home/pi/.mozilla-iot/etc/live/MYDOMAIN.mozilla-iot.org/ are empty.

Thanks!

**Comment by mrstegeman** [comment]
I believe the following steps should work. I tested them on my Raspberry Pi.

* First, download [this file](https://raw.githubusercontent.com/mozilla-iot/gateway/master/tools/manual-renew-certs-0.4.X.sh) to the RPi somewhere. Make it executable with: `chmod a+x <file>`
* Then, do the following on the RPi. Read carefully, substitute your `<values>` where necessary.

```shell
# First, remove the empty PEM files.
rm ~/.mozilla-iot/etc/archive/<domain>/*.pem

# Now, run the manual renewal script. This should succeed,
# but may throw some errors at the end about non-existent
# files. <email> should match the email you initially set up
# your domain with.
sudo <path>/manual-renew-certs-0.4.X.sh <email>

# If you got non-existent file errors above, follow below.
#
# For me, renewal created a "new" domain, so let's clean
# that up. If you don't see a <domain>-001 (or some other
# number) directory, you can skip down to where we copy
# the certs. You'll need to substitute numbers here if yours
# isn't 001.
cd ~/.mozilla-iot/etc/archive
rm -rf <domain>
mv <domain>-001 <domain>
cd ~/.mozilla-iot/etc/live
rm -rf <domain>
mv <domain>-001 <domain>
cd <domain>

# Make sure the cert1.pem file exists. It may be named
# differently.
ln -sf ../../archive/<domain>/cert1.pem cert.pem
# Make sure the chain1.pem file exists. It may be named
# differently.
ln -sf ../../archive/<domain>/chain1.pem chain.pem
# Make sure the fullchain1.pem file exists. It may be named
# differently.
ln -sf ../../archive/<domain>/fullchain1.pem fullchain.pem
# Make sure the privkey1.pem file exists. It may be named
# differently.
ln -sf ../../archive/<domain>/privkey1.pem privkey.pem

# Copy in the new certs.
cd ~/.mozilla-iot/etc/live/<domain>
cp cert.pem ../../../ssl/certificate.pem
cp privkey.pem ../../../ssl/privatekey.pem
cp chain.pem ../../../ssl/chain.pem

# Clean up duplicated renewal config.
cd ../../renewal
rm <domain>-001.conf

# Now, restart the gateway.
sudo systemctl restart mozilla-iot-gateway.service
```

**Comment by cmatheson** [comment]
@mrstegeman thanks so much! My gateway is running again great now.  A couple of additional notes for anyone that comes later:

I got errors running the following commands:
```bash
# Copy in the new certs.
cd ~/.mozilla-iot/etc/live/<domain>
cp cert.pem ../../../ssl/certificate.pem
cp privkey.pem ../../../ssl/privatekey.pem
cp chain.pem ../../../ssl/chain.pem
```
because we had already created those files in the previous block of commands (`ln -sf ...`).

After running all this, I had a valid cert in ~/.mozilla-iot/etc/live/<domain>, but the gateway was not using it yet.  I fixed that by running:

```bash
cd ~/.mozilla-iot/etc/live/cammunism.mozilla-iot.org
sudo -s
export RENEWED_LINEAGE=.
bash -x ~pi/mozilla-iot/gateway/tools/deploy-certificates.sh
```
Anyway, thanks again, glad to be back in working order.

**Comment by mrstegeman** [comment]
Perfect!
