### ISSUE TITLE
Circular reference to Device

### ISSUE THREAD

**Issue by n3b** [mozilla-iot/gateway#1503]
Whenever Event https://github.com/mozilla-iot/gateway-addon-node/blob/master/lib/event.js contains link to Device, plugin-client can't serialize it due to circular reference.
```
/var/www/gateway/src/plugin/ipc.js:159
     const jsonObj = JSON.stringify(obj);
                          ^
 
 TypeError: Converting circular structure to JSON
     at JSON.stringify (<anonymous>)
     at IpcSocket.sendJson (/var/www/gateway/src/plugin/ipc.js:159:26)
     at PluginClient.sendNotification (/var/www/gateway/src/plugin/plugin-client.js:92:26)
     at AddonManagerProxy.handleDeviceAdded (/var/www/gateway/src/plugin/addon-manager-proxy.js:81:23)
```

But if we do not pass link to Device into Event:
```
/var/www/gateway/src/plugin/addon-manager-proxy.js:360
       adapterId: event.device.adapter.id,
                               ^
 
 TypeError: Cannot read property 'adapter' of undefined
     at AddonManagerProxy.sendEventNotification (/var/www/gateway/src/plugin/addon-manager-proxy.js:360:31)
     at AddonManagerProxy.on (/var/www/gateway/src/plugin/addon-manager-proxy.js:44:12)
     at AddonManagerProxy.emit (events.js:182:13)
     at Device.eventNotify (/var/www/gateway/node_modules/gateway-addon/lib/device.js:172:26)
```

**Comment by n3b** [comment]
I think I was doing it wrong
