### ISSUE TITLE
TPLink Addon fails to start

### ISSUE THREAD

**Issue by mewt666** [mozilla-iot/gateway#1555]
The tplink addons throws a startup error and fails on installation:

`2018-12-26 19:04:17.465 INFO   : Fetching add-on https://github.com/mozilla-iot/tplink-adapter/releases/download/v0.3.3/tplink-adapter-0.3.3.tgz as /tmp/8r59XI/tplink-adapter.tar.gz
2018-12-26 19:04:18.924 INFO   : Expanding add-on /tmp/8r59XI/tplink-adapter.tar.gz into /home/mewt/.mozilla-iot/addons/tplink-adapter
2018-12-26 19:04:19.557 INFO   : Loading add-on: tplink-adapter
2018-12-26 19:04:19.815 ERROR  : tplink: Traceback (most recent call last):
2018-12-26 19:04:19.819 ERROR  : tplink:   File "/home/mewt/.mozilla-iot/addons/tplink-adapter/main.py", line 5, in <module>
2018-12-26 19:04:19.821 ERROR  : tplink:     import gateway_addon
2018-12-26 19:04:19.824 ERROR  : tplink: ImportError: No module named 'gateway_addon'
2018-12-26 19:04:19.858 INFO   : Plugin: tplink-adapter died, code = 1 restarting...
2018-12-26 19:04:20.111 ERROR  : tplink: Traceback (most recent call last):
2018-12-26 19:04:20.116 ERROR  : tplink:   File "/home/mewt/.mozilla-iot/addons/tplink-adapter/main.py", line 5, in <module>
2018-12-26 19:04:20.119 ERROR  : tplink:     import gateway_addon
2018-12-26 19:04:20.121 ERROR  : tplink: ImportError: No module named 'gateway_addon'`

**Comment by mrstegeman** [comment]
If you’ve built the gateway yourself, as it appears you have, you’ll need to install the `gateway_addon` module yourself. The instructions below are for Ubuntu/Debian/Raspbian, so you may need to adapt them if you’re using another distro.

```bash
sudo apt install python3-dev libnanomsg-dev
sudo pip3 install nnpy
sudo pip3 install git+https://github.com/mozilla-iot/gateway-addon-python.git
```
