### ISSUE TITLE
Error seen when trying to remove a device

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1642]
I tried to remove a zigbee device which was no longer on my network (i.e. I had powered it off several days ago) and today I tried to remove it using the UI. It was removed from the UI successfully, but generated the following errors in the log:
```
2019-02-11 10:46:00.317 ERROR  : Error getting thing description for thing with id zb-000b57fffeb13785
2019-02-11 10:46:00.317 ERROR  : Error: Error: Unable to find thing with id: zb-000b57fffeb13785
2019-02-11 10:46:00.356 ERROR  : Error getting thing description for thing with id zb-000b57fffeb13785
2019-02-11 10:46:00.357 ERROR  : Error: Error: Unable to find thing with id: zb-000b57fffeb13785
2019-02-11 10:46:01.320 ERROR  : WebSocket opened on nonexistent thing zb-000b57fffeb13785
2019-02-11 10:46:01.328 ERROR  : WebSocket opened on nonexistent thing zb-000b57fffeb13785
2019-02-11 10:46:01.331 ERROR  : WebSocket opened on nonexistent thing zb-000b57fffeb13785
2019-02-11 10:46:01.442 ERROR  : WebSocket sendMessage failed Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at sendMessage (/home/dhylands/moziot/gateway/build/webpack:/src/controllers/things_controller.js:357:1)
    at WebSocket.websocket.on (/home/dhylands/moziot/gateway/build/webpack:/src/controllers/things_controller.js:463:1)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:718:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at TLSSocket.socketOnData (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:788:35)
2019-02-11 10:46:01.507 ERROR  : WebSocket opened on nonexistent thing zb-000b57fffeb13785
2019-02-11 10:46:01.510 ERROR  : WebSocket sendMessage failed Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at sendMessage (/home/dhylands/moziot/gateway/build/webpack:/src/controllers/things_controller.js:357:1)
    at WebSocket.websocket.on (/home/dhylands/moziot/gateway/build/webpack:/src/controllers/things_controller.js:463:1)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:718:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at TLSSocket.socketOnData (/home/dhylands/moziot/gateway/node_modules/express-ws/node_modules/ws/lib/websocket.js:788:35)
2019-02-11 10:46:01.517 ERROR  : WebSocket opened on nonexistent thing zb-000b57fffeb13785
```

**Comment by mrstegeman** [comment]
We caught the error and just logged it. Not a huge issue. I opened #1651 to clean up the log a bit.

**Comment by dhylands** [comment]
when highlighted in red, it looks like something alot more serious that it was :)
