### ISSUE TITLE
gateway crashed in dnssd

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1650]
I rebooted my Wifi modem (the one that connects to my ISP) this morning and the gateway crashed.
The last thing on the console was the following error:
```
2019-02-13 06:55:23.656 ERROR  : 
2019-02-13 06:55:23.657 ERROR  : /home/dhylands/moziot/gateway/node_modules/dnssd/lib/ExpiringRecordCollection.js:243
      this._getRelatedRecords(record.namehash).forEach(function (related) {
                                               ^
2019-02-13 06:55:23.657 ERROR  : TypeError: Cannot read property 'equals' of undefined
    at /home/dhylands/moziot/gateway/node_modules/dnssd/lib/ExpiringRecordCollection.js:245:21
    at Array.forEach (<anonymous>)
    at ExpiringRecordCollection.flushRelated (/home/dhylands/moziot/gateway/node_modules/dnssd/lib/ExpiringRecordCollection.js:243:48)
    at /home/dhylands/moziot/gateway/node_modules/dnssd/lib/NetworkInterface.js:329:39
    at Array.forEach (<anonymous>)
    at NetworkInterface._addToCache (/home/dhylands/moziot/gateway/node_modules/dnssd/lib/NetworkInterface.js:328:19)
    at NetworkInterface._onMessage (/home/dhylands/moziot/gateway/node_modules/dnssd/lib/NetworkInterface.js:304:10)
    at Socket.<anonymous> (/home/dhylands/moziot/gateway/node_modules/dnssd/lib/NetworkInterface.js:222:14)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
```
It looks like a bug in dnssd and not the gateway itself, but I thought I would record the error in case it was useful.

**Comment by mrstegeman** [comment]
Hopefully we can just stop using this module when we switch to OpenWrt and do something via `uci` instead. We've encountered other issues with this module as well, and it seems unmaintained.

**Comment by mrstegeman** [comment]
For later: https://openwrt.org/docs/guide-user/network/zeroconfig/zeroconf
