### ISSUE TITLE
My gateway's cert renewal failed, with "Malformed account ID in KeyID header URL"

### ISSUE THREAD

**Issue by dholbert** [mozilla-iot/gateway#1792]
My mozilla-iot gateway ( https://eagle.mozilla-iot.org/ ) had its cert expire yesterday, and its renewal seems to have failed.

Here is the relevant logging (with a few long credential-looking-strings redacted with `[...SNIP...]`:

---

```
2019-03-16 00:00:07,632:DEBUG:acme.client:Storing nonce: tNMn5v-iDfJ-VA[...SNIP...]AM
2019-03-16 00:00:07,633:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "value": "eagle.mozilla-iot.org",\n      "type": "dns"\n    }\n  ]\n}'
2019-03-16 00:00:07,671:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "ey[...SNIP...]fQ",
  "payload": "ew[...SNIP...]n0",
  "signature": "hU[...SNIP...]Cw"
}
2019-03-16 00:00:07,748:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 400 209
2019-03-16 00:00:07,752:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Content-Type: application/problem+json
Content-Length: 209
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 87mGWb8o-E2yAyxdF76IiJaLPyJI2R8FBwReiF-Hrms
Expires: Sat, 16 Mar 2019 07:00:07 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 16 Mar 2019 07:00:07 GMT
Connection: close

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Malformed account ID in KeyID header URL: \"https://acme-v01.api.letsencrypt.org/acme/reg/48bd2479ee653f423d40723bb6eed5ec\"",
  "status": 400
}
2019-03-16 00:00:07,754:WARNING:certbot.renewal:Attempting to renew cert (eagle.mozilla-iot.org) from /home/pi/.mozilla-iot/etc/renewal/eagle.mozilla-iot.org.conf produced an unexpected error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Malformed account ID in KeyID header URL: "https://acme-v01.api.letsencrypt.org/acme/reg/48bd2479ee653f423d40723bb6eed5ec". Skipping.
2019-03-16 00:00:07,760:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1168, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 305, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 335, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 367, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 824, in new_order
    return self.client.new_order(csr_pem)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 650, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 94, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1130, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1147, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 999, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Malformed account ID in KeyID header URL: "https://acme-v01.api.letsencrypt.org/acme/reg/48bd2479ee653f423d40723bb6eed5ec"
```

---

**Comment by dholbert** [comment]
My letsencrypt.log has many copies of this error over the past month (first one on March 14th, a month before my cert expiration date... I wish I'd noticed it sooner. :) )

**Comment by dholbert** [comment]
I'm using gateway version 0.7.0, according to `~/mozilla-iot/gateway/build-info.txt`

Let me know if there's any other information I can gather or any workarounds/steps that I should try. For now, no web browser will load the web interface (no click-through workaround, because the site uses HSTS which prevents the ability to click through SSL errors).

**Comment by mrstegeman** [comment]
For now, you should still be able to access the gateway locally, either via `https://gateway.local` or `https://<ip-address>`.

We're hoping to get 0.8 released this week. I completely reworked certificate renewal for this release, so I'm hoping that it will just resolve your issues.

If you're unable to access locally, please let us know so we can figure out a workaround.

**Comment by dholbert** [comment]
Thanks for the response -- yeah, `gateway.local` does work (there's an SSL error page but I can click through it).

Looking forward to the update!

**Comment by dholbert** [comment]
I was able to apply the 0.8 update (via the web interface, accessed via https://gateway.local ), and after the update applied, it seems the cert renewal was successful.

Hooray / thanks!

**Comment by mrstegeman** [comment]
Yay!
