### ISSUE TITLE
Error: Cannot find module 'gateway-addon'

### ISSUE THREAD

**Issue by mowi22** [mozilla-iot/gateway#1799]
I hae a custom build of the gateway on on an rpi. I've been having issues getting the gateway to recognize the `gateway-addons` in the `node_modules` folder. It is listed as a dependency. 
Here are my system details
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```

I get this error every time i run `npm-start`

```
2019-04-18 05:26:47.572 ERROR  : onvif: { Error: Cannot find module 'gateway-addon'
2019-04-18 05:26:47.574 ERROR  : onvif:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-04-18 05:26:47.577 ERROR  : onvif:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-04-18 05:26:47.579 ERROR  : onvif:     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-04-18 05:26:47.590 ERROR  : onvif:     at require (internal/modules/cjs/helpers.js:22:18)
2019-04-18 05:26:47.592 ERROR  : onvif:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/onvif-adapter/lib/onvif-adapter.js:6:29)
2019-04-18 05:26:47.594 ERROR  : onvif:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-04-18 05:26:47.597 ERROR  : onvif:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-04-18 05:26:47.599 ERROR  : onvif:     at Module.load (internal/modules/cjs/loader.js:599:32)
2019-04-18 05:26:47.601 ERROR  : onvif:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-04-18 05:26:47.604 ERROR  : onvif:     at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```

**Here are my dependencies** 

```json
  "dependencies": {
    "ajv": "^6.10.0",
    "archiver": "^3.0.0",
    "asn1.js": "^5.0.1",
    "bcryptjs": "^2.4.3",
    "bindings": "^1.5.0",
    "bluebird": "^3.5.4",
    "body-parser": "^1.18.3",
    "callsites": "^3.1.0",
    "compression": "^1.7.4",
    "config": "^3.1.0",
    "csv-parse": "^4.4.0",
    "dnssd": "^0.4.1",
    "express": "^4.16.4",
    "express-fileupload": "^1.1.4",
    "express-handlebars": "^3.0.2",
    "express-promise-router": "^3.0.3",
    "express-ws": "^4.0.0",
    "gateway-addon": "https://github.com/mozilla-iot/gateway-addon-node#v0.8.0",
    "greenlock": "^2.7.17",
    "http-proxy": "^1.17.0",
    "ip-regex": "^4.0.0",
    "jsonwebtoken": "^8.5.1",
    "le-challenge-dns": "^3.0.3",
    "le-challenge-fs": "^2.0.8",
    "mkdirp": "^0.5.1",
    "nanomsg": "^4.0.2",
    "ncp": "^2.0.0",
    "nocache": "^2.0.0",
    "node-fetch": "^2.3.0",
    "node-getopt": "^0.3.2",
    "promisepipe": "^3.0.0",
    "rimraf": "^2.6.3",
    "source-map-support": "^0.5.12",
    "sqlite3": "^4.0.6",
    "string-format": "^2.0.0",
    "tar": "^4.4.8",
    "tmp": "^0.1.0",
    "uuid": "^3.3.2",
    "web-push": "^3.3.3",
    "winston": "^3.2.1",
    "winston-daily-rotate-file": "^3.8.0",
    "ws": "^6.2.1"
  },
```
Let me know what I'm missing. I've cleared and recloned and am still getting the same issue.

**Comment by mowi22** [comment]
Any help on this?

**Comment by mrstegeman** [comment]
Random question that I didn't ask before, but where have you installed the gateway (what's the directory path)?

**Comment by flatsiedatsie** [comment]
It would seem here?
`/home/pi/.mozilla-iot/addons/onvif-adapter/lib/onvif-adapter.js`

I'm only new to this myself, but is the name in the package.json the same as the folder name?

**Comment by jcaron23** [comment]
For those having this issue, make sure that you correctly do the `nvm` steps of the installation instructions. Once that is done, remove the node-modules folder and do `npm install` again.
