### ISSUE TITLE
Port Validation Error on Startup

### ISSUE THREAD

**Issue by malceore** [mozilla-iot/gateway#1812]
Hello, I have tried installing and starting gateway using the instructions here and also in the Docker repository but I keep experiencing this issue upon start:
```
$ npm start
> webthings-gateway@0.8.1 start /home/b/Code/gateway
> webpack --display errors-only && node build/gateway.js
ℹ ｢atl｣: Using typescript@3.4.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /home/b/Code/gateway/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 5003ms
Creating database: /home/b/.mozilla-iot/test/config/db.sqlite3
2019-04-20 08:14:09.916 ERROR  : Failed to import platform utilities for linux-unknown
2019-04-20 08:14:10.211 ERROR  : 
2019-04-20 08:14:10.212 ERROR  : /home/b/Code/gateway/node_modules/dnssd/lib/validate.js:102
    throw new ValidationError('Port must be an integer between 0 and 65535, got %s', num);
          ^
2019-04-20 08:14:10.212 ERROR  : ValidationError: Port must be an integer between 0 and 65535, got 0
    at Object.port (/home/b/Code/gateway/node_modules/dnssd/lib/validate.js:102:11)
    at new Advertisement (/home/b/Code/gateway/node_modules/dnssd/lib/Advertisement.js:56:12)
    at Object.Advertisement (/home/b/Code/gateway/node_modules/dnssd/lib/Advertisement.js:47:12)
    at new DNSserviceDiscovery (/home/b/Code/gateway/build/webpack:/src/mdns-server.js:68:1)
    at Object../src/mdns-server.js (/home/b/Code/gateway/build/webpack:/src/mdns-server.js:301:1)
    at __webpack_require__ (/home/b/Code/gateway/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/app.js (/home/b/Code/gateway/build/webpack:/src/app.js:39:20)
    at __webpack_require__ (/home/b/Code/gateway/build/webpack:/webpack/bootstrap:19:1)
    at /home/b/Code/gateway/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/b/Code/gateway/build/gateway.js:88:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webthings-gateway@0.8.1 start: `webpack --display errors-only && node build/gateway.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webthings-gateway@0.8.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/b/.npm/_logs/2019-04-20T12_14_10_233Z-debug.log
```

I was able to comment out the port validation on line 56 of the below file, the gateway server seems to start normally on my local environment.
```
gateway/node_modules/dnssd/lib/Advertisement.js
```

Here are my node, nvm and linux versions. Please let me know if I can provide anything else, I just wanted to bring this to your attention and support the project's development.
```
b@test:~/Code/gateway$ nvm version
v8.16.0
b@test:~/Code/gateway$ node --version
v8.16.0
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

**Comment by mrstegeman** [comment]
It looks like you're somehow running in test mode. Can you post the content of the following files and commands:
* `/home/b/Code/gateway/config/default.js`
* `/home/b/Code/gateway/config/test.js`
* `/home/b/.mozilla-iot/config/local.json`
* `echo "${MOZIOT_HOME}"`
* `echo "${NODE_ENV}"`

**Comment by malceore** [comment]
How would I disable test mode? Those environment variables don't exist for me or they are null. Also my directory seems to look like this with an extra test directory inside:
/home/b/.mozilla-iot/test/config/local.json

Attached those other files for examination:
[default.js.txt](https://github.com/mozilla-iot/gateway/files/3105162/default.js.txt)
[test.js.txt](https://github.com/mozilla-iot/gateway/files/3105163/test.js.txt)
[local.json.txt](https://github.com/mozilla-iot/gateway/files/3105164/local.json.txt)

Let me know if there is anything else I can get you.

**Comment by mrstegeman** [comment]
What about `$NODE_CONFIG_ENV`? Is that one set?

From your log, I can tell that you're in test mode because:
1. The port is 0.
2. Your profile directory has `/test` appended.

Those things are both specified in the test config, `test.js`.

**Comment by malceore** [comment]
Okay so my solution was to simply rename the test.js to something else and it seems Gateway started normally. Closing out this issue.

**Comment by mrstegeman** [comment]
Huh, very strange. Glad it works, though!
