### ISSUE TITLE
Syntax error while starting gateway?

### ISSUE THREAD

**Issue by grbesd1** [mozilla-iot/gateway#1964]
Hi Guys,

I'm running gateway on embedded linux arm platform. 
1. "npm install" from gateway folder - All packages are installed no error.
2. "npm start" - I'm getting syntax error.
```
~/gateway # npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.10.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle webthings-gateway@0.8.1~prestart: webthings-gateway@0.8.1
npm info lifecycle webthings-gateway@0.8.1~start: webthings-gateway@0.8.1

> webthings-gateway@0.8.1 start /home/root/gateway
> webpack --display errors-only && node build/gateway.js

��ℹ ��｢atl��｣: Using typescript@3.5.2 from typescript
��ℹ ��｢atl��｣: Using tsconfig.json from /home/root/gateway/tsconfig.json
��ℹ ��｢atl��｣: Checking started in a separate process...
��ℹ ��｢atl��｣: Time: 20199ms
/home/root/gateway/build/gateway.js:2695
  async addonEnabled(packageName) {
        ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm verb lifecycle webthings-gateway@0.8.1~start: unsafe-perm in lifecycle true
npm verb lifecycle webthings-gateway@0.8.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/root/gateway/node_modules/.bin:/sbin:/n
npm verb lifecycle webthings-gateway@0.8.1~start: CWD: /home/root/gateway
npm info lifecycle webthings-gateway@0.8.1~start: Failed to exec start script
npm verb stack Error: webthings-gateway@0.8.1 start: `webpack --display errors-only && node build/gateway.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid webthings-gateway@0.8.1
npm verb cwd /home/root/gateway
```

I'm i missing any package or dependencies here. It's a bare OS system. No browser, No UI or desktop environment.

**Comment by mrstegeman** [comment]
Looks like you’re using Node v6, which we no longer support. You’ll need Node v8+.
