### ISSUE TITLE
Raspberry Pi 4 support

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1965]
I am curious if there are any reasons why the WebThings Gateway wouldn't be able to run on the Raspberry Pi 4 out of the gate. If any 'snags' can be foreseen, is there any prediction on how long it would take to make the software compatible?

This because I have to make a purchase or 4+ new Pi's that will be running the WebThings Gateway, and I'd rather get the Pi 4 in anticipation of local voice control running on the device simultaneously.

**Comment by flatsiedatsie** [comment]
Perhaps put more succinctly: will the next Raspberry Pi image support the Pi 4?

**Comment by mrstegeman** [comment]
We'll target the latest Raspbian for our next release, which should theoretically support the RPi 4. I believe most of our team has ordered devices, but they're all back-ordered, so testing will be difficult for the next month or so.

**Comment by benfrancis** [comment]
As a user I want to install WebThings Gateway on a Raspberry Pi 4

**Comment by flatsiedatsie** [comment]
I have three arriving tomorrow. I could send you one?

**Comment by benfrancis** [comment]
@flatsiedatsie wrote:
> I have three arriving tomorrow. I could send you one?

Ah, that's helpful thanks. We won't ask you to send us one but we may call on you to test a pre-release 0.9 build for us if ours don't arrive on time!

**Comment by flatsiedatsie** [comment]
@benfrancis I'd be happy to (and my offer still stands)

**Comment by flatsiedatsie** [comment]
Probably unsurprisingly the existing 8.1 image did not seem to boot on the Raspberry Pi 4.

**Comment by dhylands** [comment]
Try this one instead: https://s3-us-west-1.amazonaws.com/mozillagatewayimages/images/gateway-0.9.0-pre1.img.zip

**Comment by flatsiedatsie** [comment]
It works! 

The only strange thing I noticed is that is seems like thing names aren't coming through:

![gateway-undefined](https://user-images.githubusercontent.com/805405/60372646-ca7c8300-99ec-11e9-82ff-a884de28518e.png)

But it could be an issue with my code.

Yep, seems like an issue with the add-ons I created, since the Mi Flora add-on works as normal.

**Comment by flatsiedatsie** [comment]
off-topic, but could it be this? Should `this.name` be replaced with `this.title`?  https://github.com/mozilla-iot/gateway/issues/1948

**Comment by mrstegeman** [comment]
`this.name` should still work fine. Seems like the gateway-addon package was maybe not updated in this image or something.

**Comment by flatsiedatsie** [comment]
@mrstegeman Could it be cause the add-ons have [their own versions](https://github.com/createcandle/Candle-manager-addon/blob/master/pkg/candle_adapter.py#L1182) of the get_as_dict functions?

Back on topic, I have noticed a _lot_ of this in the log:

```
2019-06-29 00:00:01.026 INFO   : thing-url: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-06-29 00:00:01.053 INFO   : thing-url: Loading add-on for thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2019-06-29 00:00:01.346 INFO   : thing-url: Starting mDNS discovery
2019-06-29 00:00:01.433 ERROR  : thing-url: events.js:183
2019-06-29 00:00:01.434 ERROR  : thing-url:       throw er; // Unhandled 'error' event
2019-06-29 00:00:01.434 ERROR  : thing-url:       ^
2019-06-29 00:00:01.435 ERROR  : thing-url: 
2019-06-29 00:00:01.435 ERROR  : thing-url: Error: send ENETUNREACH 224.0.0.251:5353
2019-06-29 00:00:01.436 ERROR  : thing-url:     at SendWrap.afterSend [as oncomplete] (dgram.js:499:11)
2019-06-29 00:00:01.441 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 3000
2019-06-29 00:00:04.893 INFO   : thing-url: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-06-29 00:00:04.922 INFO   : thing-url: Loading add-on for thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2019-06-29 00:00:05.223 INFO   : thing-url: Starting mDNS discovery
2019-06-29 00:00:20.298 ERROR  : thing-url: events.js:183
2019-06-29 00:00:20.298 ERROR  : thing-url:       throw er; // Unhandled 'error' event
2019-06-29 00:00:20.299 ERROR  : thing-url:       ^
2019-06-29 00:00:20.300 ERROR  : thing-url: 
2019-06-29 00:00:20.301 ERROR  : thing-url: Error: send ENETUNREACH 224.0.0.251:5353
2019-06-29 00:00:20.302 ERROR  : thing-url:     at SendWrap.afterSend [as oncomplete] (dgram.js:499:11)
2019-06-29 00:00:20.304 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 4000
2019-06-29 00:00:24.725 INFO   : thing-url: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-06-29 00:00:24.751 INFO   : thing-url: Loading add-on for thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2019-06-29 00:00:25.044 INFO   : thing-url: Starting mDNS discovery
2019-06-29 00:00:25.111 ERROR  : thing-url: events.js:183
2019-06-29 00:00:25.112 ERROR  : thing-url:       throw er; // Unhandled 'error' event
2019-06-29 00:00:25.112 ERROR  : thing-url:       ^
2019-06-29 00:00:25.113 ERROR  : thing-url: 
```

**Comment by dhylands** [comment]
> `this.name` should still work fine. Seems like the gateway-addon package was maybe not updated in this image or something.

I confirmed that all of the files in the /home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib of the 0.9.0-pre1 image are identical to the latest master in the gateway-addon-node repository.

**Comment by mrstegeman** [comment]
@flatsiedatsie Yes, that would actually cause the issue you’re seeing.

**Comment by flatsiedatsie** [comment]
@mrstegeman Ok, I'll add the this.title into it for the next version.

**Comment by benfrancis** [comment]
This seems to be working, please file follow-up bugs for any issues discovered during testing.
