### ISSUE TITLE
Secondary captive portal failed to start on turris omnia

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2003]
Not sure if this is a real problem or not, but I figured I'd log the issue since I saw it.

I was connected via the WAN port (with holes punched through the firewall) and I setup the Wifi and then chose skip for the tunnel. I saw this in the log
```
2019-07-09 21:45:56.751 INFO   : Creating database: /.mozilla-iot/log/logs.sqlite3
2019-07-09 21:45:57.731 INFO   : router-setup: startCaptivePortal: ipaddr: 192.168.2.1
2019-07-09 21:45:58.238 INFO   : Redirecting from 80 to 8080 (for 192.168.2.1)
2019-07-09 21:45:58.337 INFO   : Redirecting from 443 to 4443 (for 192.168.2.1)
2019-07-09 21:45:59.798 INFO   : Starting Router Setup
2019-07-09 21:45:59.831 INFO   : DNS config is: turris
2019-07-09 21:45:59.836 INFO   : Service Discovery: changing profile - local domain is now: turris
2019-07-09 21:45:59.842 ERROR  : Service Discovery: failed to change state
2019-07-09 21:56:21.835 INFO   : router-setup: handleCaptive: /
2019-07-09 21:56:21.837 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:21.839 INFO   : router-setup: handleRoot: router unconfigured; redirecting to router-setup
2019-07-09 21:56:21.886 INFO   : router-setup: handleCaptive: /router-setup
2019-07-09 21:56:21.888 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:22.033 INFO   : router-setup: handleCaptive: /optimized-images/wordmark.svg
2019-07-09 21:56:22.034 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:22.093 INFO   : router-setup: handleCaptive: /fonts/opensans-regular.woff2
2019-07-09 21:56:22.094 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:22.100 INFO   : router-setup: handleCaptive: /fonts/ZillaSlab-Bold.woff2
2019-07-09 21:56:22.101 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:22.128 INFO   : router-setup: handleCaptive: /favicon.ico
2019-07-09 21:56:22.130 INFO   : router-setup: handleCaptive: unknown path, skipping.
2019-07-09 21:56:56.991 INFO   : router-setup: stopCaptivePortal
2019-07-09 21:57:05.665 INFO   : router-setup: defineNetwork: ssid: WebThings Gateway
2019-07-09 21:57:06.100 INFO   : router-setup: waitForWifi: connection found
2019-07-09 21:57:06.102 INFO   : router-setup: startSecondaryCaptivePortal: ipaddr: 192.168.2.1
2019-07-09 21:57:06.231 ERROR  : router-setup: handleCreating: failed to start secondary captive portal: { Error: queryA ESERVFAIL acme-v02.api.letsencrypt.org
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ESERVFAIL',
  errno: 'ESERVFAIL',
  syscall: 'queryA',
  hostname: 'acme-v02.api.letsencrypt.org' }
2019-07-09 21:57:06.233 INFO   : Stopping Router Setup
2019-07-09 21:57:06.251 INFO   : HTTP server listening on port 8080
2019-07-09 21:57:16.418 INFO   : Checking for add-on updates...
2019-07-09 21:57:17.165 INFO   : Finished updating add-ons
2019-07-09 21:57:36.691 INFO   : Tunnel name is set to: Not set.
2019-07-09 21:57:36.692 INFO   : Local mDNS Service Domain Name is: turris
```

**Comment by mrstegeman** [comment]
I wonder if the Turris maybe didn't have a DNS server set?

**Comment by dhylands** [comment]
I was able to ping acme-v02.api.letsencrypt.org but that was after I had skipped the tunnel setup.

**Comment by mrstegeman** [comment]
Closing since the second portal is gone.
