### ISSUE TITLE
Got an error trying to reclaim my token

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2037]
I got the following error while trying to reclaim my domain:

http://gateway.local/%3C!DOCTYPE%20html%3E%3Chtml%20lang=%22en%22%3E%3Chead%3E%3Cmeta%20charset=%22utf-8%22%3E%3Ctitle%3EError%3C/title%3E%3C/head%3E%3Cbody%3E%3Cpre%3ETypeError:%20Cannot%20read%20property%20'then&%2339;%20of%20undefined%3Cbr%3E%20 %20 at%20Object../src/app.js.TunnelService.switchToHttps%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:427:1)%3Cbr%3E%20 %20 at%20cb%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)%3Cbr%3E%20 %20 at%20Object.register%20(/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:205:1)%3Cbr%3E%20 %20 at%20<anonymous>%3C/pre%3E%3C/body%3E%3C/html%3E

**Comment by dhylands** [comment]
The second time I tried, everything worked fine.

**Comment by mrstegeman** [comment]
That translates to:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error</title>
  </head>
  <body>
    <pre>TypeError: Cannot read property 'then&#39; of undefined<br>    at Object../src/app.js.TunnelService.switchToHttps (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:427:1)<br>    at cb (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)<br>    at Object.register (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:205:1)<br>    at</pre>
  </body>
</html>
```

Which then translates to:

```
TypeError: Cannot read property 'then&#39; of undefined
    at Object../src/app.js.TunnelService.switchToHttps (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:427:1)
    at cb (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)
    at Object.register (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:205:1)
    at
```

**Comment by mrstegeman** [comment]
Do you have a `Registration failed: ` entry in your log, by chance?

**Comment by dhylands** [comment]
I got the following:
```
2019-06-26 00:45:33.444 ERROR  : [acme-v2] handled(?) rejection as errback:
2019-06-26 00:45:33.446 ERROR  : Error: certificate is not yet valid
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
2019-06-26 00:45:33.449 ERROR  : Registration failed: { Error: certificate is not yet valid
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'CERT_NOT_YET_VALID' }
2019-06-26 00:45:33.705 ERROR  : TypeError: Cannot read property 'then' of undefined
    at Object../src/app.js.TunnelService.switchToHttps (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:427:1)
    at cb (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/settings_controller.js:121:1)
    at Object.register (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:205:1)
    at <anonymous>
2019-06-26 00:45:34.724 ERROR  : Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/pi/mozilla-iot/gateway/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/pi/mozilla-iot/gateway/node_modules/express/lib/response.js:170:12)
    at Socket.pagekiteProcess.stdout.on (/home/pi/mozilla-iot/gateway/build/webpack:/src/ssltunnel.js:111:1)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
```
I noticed that the date hadn't yet changed (i.e. it was still set at June 26 which I think is the date of the base image.

**Comment by dhylands** [comment]
We should probably set the date and time.

Searching around the net, it seems that running
```
timedatectl set-local-rtc 0
timedatectl set-ntp 1
```
after establishing the network connection seems to work. For testing you can use
```
timedatectl status
```
