### ISSUE TITLE
Upgrade error on highly modified system

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2099]
This is not an issue, but I thought I'd share anyway.

I have an 8.1 gateway that I modified to boot into a desktop environment and run a fullscreen kiosk browser.

Without thinking, I tried updating it using the gateway's upgrade functionality.

Something went wrong there:
```
+ MOZIOT_HOME=/home/pi/.mozilla-iot
+ args=
+ start_task=start
+ is_docker_container
+ '[' -f /.dockerenv ']'
+ grep -q ':\/docker\/' /proc/1/cgroup
+ return 1
+ start_task=run-only
+ '[' '!' -f .post_upgrade_complete ']'
+ mkdir -p /home/pi/.mozilla-iot/log
+ run_app
+ export NVM_DIR=/home/pi/.nvm
+ NVM_DIR=/home/pi/.nvm
+ '[' '!' -s /home/pi/.nvm/nvm.sh ']'
+ . /home/pi/.nvm/nvm.sh
++ NVM_SCRIPT_SOURCE=']'
++ '[' -z '' ']'
++ export NVM_CD_FLAGS=
++ NVM_CD_FLAGS=
++ nvm_has unsetopt
++ type unsetopt
++ '[' -z /home/pi/.nvm ']'
++ unset NVM_SCRIPT_SOURCE
++ nvm_process_parameters
++ local NVM_AUTO_MODE
++ NVM_AUTO_MODE=use
++ nvm_supports_source_options
+++ echo '[ $# -gt 0 ] && echo $1'
+++ . /dev/stdin yes
++ '[' _yes = _yes ']'
++ '[' 0 -ne 0 ']'
++ nvm_auto use
++ local NVM_MODE
++ NVM_MODE=use
++ local VERSION
++ '[' _use = _install ']'
++ '[' _use = _use ']'
+++ nvm_resolve_local_alias default
+++ nvm_echo
+++ command printf '%s\n' ''
++ VERSION=N/A
++ '[' -n N/A ']'
++ nvm use --silent N/A
++ '[' 3 -lt 1 ']'
++ local DEFAULT_IFS
+++ echo t
+++ tr t '\t'
++ DEFAULT_IFS=' 	
'
++ '[' ' 	
' '!=' ' 	
' ']'
++ local COMMAND
++ COMMAND=use
++ shift
++ local VERSION
++ local ADDITIONAL_PARAMETERS
++ case $COMMAND in
++ local PROVIDED_VERSION
++ local NVM_USE_SILENT
++ NVM_USE_SILENT=0
++ local NVM_DELETE_PREFIX
++ NVM_DELETE_PREFIX=0
++ local NVM_LTS
++ '[' 2 -ne 0 ']'
++ case "$1" in
++ NVM_USE_SILENT=1
++ shift
++ '[' 1 -ne 0 ']'
++ case "$1" in
++ '[' -n N/A ']'
++ PROVIDED_VERSION=N/A
++ shift
++ '[' 0 -ne 0 ']'
++ '[' -n '' ']'
++ '[' -z N/A ']'
+++ nvm_match_version N/A
+++ local NVM_IOJS_PREFIX
++++ nvm_iojs_prefix
++++ nvm_echo iojs
++++ command printf '%s\n' iojs
+++ NVM_IOJS_PREFIX=iojs
+++ local PROVIDED_VERSION
+++ PROVIDED_VERSION=N/A
+++ case "_$PROVIDED_VERSION" in
+++ nvm_version N/A
+++ local PATTERN
+++ PATTERN=N/A
+++ local VERSION
+++ '[' -z N/A ']'
+++ '[' N/A = current ']'
+++ local NVM_NODE_PREFIX
++++ nvm_node_prefix
++++ nvm_echo node
++++ command printf '%s\n' node
+++ NVM_NODE_PREFIX=node
+++ case "_${PATTERN}" in
++++ nvm_ls N/A
++++ command tail -1
++++ tail -1
++++ local PATTERN
++++ PATTERN=N/A
++++ local VERSIONS
++++ VERSIONS=
++++ '[' N/A = current ']'
++++ local NVM_IOJS_PREFIX
+++++ nvm_iojs_prefix
+++++ nvm_echo iojs
+++++ command printf '%s\n' iojs
++++ NVM_IOJS_PREFIX=iojs
++++ local NVM_NODE_PREFIX
+++++ nvm_node_prefix
+++++ nvm_echo node
+++++ command printf '%s\n' node
++++ NVM_NODE_PREFIX=node
++++ local NVM_VERSION_DIR_IOJS
+++++ nvm_version_dir iojs
+++++ local NVM_WHICH_DIR
+++++ NVM_WHICH_DIR=iojs
+++++ '[' -z iojs ']'
+++++ '[' iojs = new ']'
+++++ '[' _iojs = _iojs ']'
+++++ nvm_echo /home/pi/.nvm/versions/io.js
+++++ command printf '%s\n' /home/pi/.nvm/versions/io.js
++++ NVM_VERSION_DIR_IOJS=/home/pi/.nvm/versions/io.js
++++ local NVM_VERSION_DIR_NEW
+++++ nvm_version_dir new
+++++ local NVM_WHICH_DIR
+++++ NVM_WHICH_DIR=new
+++++ '[' -z new ']'
+++++ '[' new = new ']'
+++++ nvm_echo /home/pi/.nvm/versions/node
+++++ command printf '%s\n' /home/pi/.nvm/versions/node
++++ NVM_VERSION_DIR_NEW=/home/pi/.nvm/versions/node
++++ local NVM_VERSION_DIR_OLD
+++++ nvm_version_dir old
+++++ local NVM_WHICH_DIR
+++++ NVM_WHICH_DIR=old
+++++ '[' -z old ']'
+++++ '[' old = new ']'
+++++ '[' _old = _iojs ']'
+++++ '[' _old = _old ']'
+++++ nvm_echo /home/pi/.nvm
+++++ command printf '%s\n' /home/pi/.nvm
++++ NVM_VERSION_DIR_OLD=/home/pi/.nvm
++++ case "${PATTERN}" in
++++ nvm_resolve_local_alias N/A
++++ '[' -z N/A ']'
++++ local VERSION
++++ local EXIT_CODE
+++++ nvm_resolve_alias N/A
+++++ '[' -z N/A ']'
+++++ local PATTERN
+++++ PATTERN=N/A
+++++ local ALIAS
+++++ ALIAS=N/A
+++++ local ALIAS_TEMP
+++++ local SEEN_ALIASES
+++++ SEEN_ALIASES=N/A
+++++ true
++++++ nvm_alias N/A
++++++ echo
+++++ ALIAS_TEMP=
+++++ '[' -z '' ']'
+++++ break
+++++ '[' -n N/A ']'
+++++ '[' _N/A '!=' _N/A ']'
+++++ nvm_validate_implicit_alias N/A
+++++ return 2
++++ VERSION=
++++ EXIT_CODE=2
++++ '[' -z '' ']'
++++ return 2
+++++ nvm_ensure_version_prefix N/A
+++++ local NVM_VERSION
++++++ nvm_strip_iojs_prefix N/A
++++++ local NVM_IOJS_PREFIX
++++++ command sed -e 's/^\([0-9]\)/v\1/g'
++++++ sed -e 's/^\([0-9]\)/v\1/g'
+++++++ nvm_iojs_prefix
+++++++ nvm_echo iojs
+++++++ command printf '%s\n' iojs
++++++ NVM_IOJS_PREFIX=iojs
++++++ '[' N/A = iojs ']'
++++++ nvm_echo N/A
++++++ command printf '%s\n' N/A
+++++ NVM_VERSION=N/A
+++++ nvm_is_iojs_version N/A
+++++ case "${1-}" in
+++++ return 1
+++++ nvm_echo N/A
+++++ command printf '%s\n' N/A
++++ PATTERN=N/A
++++ '[' N/A = N/A ']'
++++ return
+++ VERSION=
+++ '[' -z '' ']'
+++ nvm_echo N/A
+++ command printf '%s\n' N/A
+++ return 3
++ VERSION=N/A
```

Then:

```
nvm run start
Found '/home/pi/mozilla-iot/gateway/.nvmrc' with version <lts/carbon>
N/A: version "" is not yet installed.

You need to run "nvm install " to install it before using it.
```

So I ran `nvm install`, which seemed to work.

And then it stops on `node build/gateway.js`

```
+ echo 'Starting gateway ...'
Starting gateway ...
+ npm run run-only --

> webthings-gateway@0.8.1 run-only /home/pi/mozilla-iot/gateway
> node build/gateway.js

Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-08-23 12:49:10.677 INFO   : Opening database: /home/pi/.mozilla-iot/log/logs.sqlite3
2019-08-23 12:49:12.558 ERROR  : Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Promise (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:151:1)
    at new Promise (<anonymous>)
    at startHttpGateway (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:150:1)
    at startGateway (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:372:1)
    at ./src/app.js.migration.then.then (/home/pi/mozilla-iot/gateway/build/webpack:/src/app.js:330:1)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webthings-gateway@0.8.1 run-only: `node build/gateway.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webthings-gateway@0.8.1 run-only script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

Again, this is most likely due to my modifications, but I thought I'd share since it might be interesting or useful in some unforeseen way.

**Comment by flatsiedatsie** [comment]
After noticing the `Error: listen EADDRINUSE :::8080` I rebooted the system, and hey presto, it works again.

**Comment by flatsiedatsie** [comment]
After manually disabling all the add-ons, an then hitting the upgrade button, the upgrade worked.

**Comment by mrstegeman** [comment]
Seems like you got things working.
