### ISSUE TITLE
Failed to parse add-on list

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2306]
I  noticed something odd in my logs just now:

```
2019-11-21 21:47:46.419 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.mozilla-iot.org api.mozilla-iot.org:8443
    at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.mozilla-iot.org api.mozilla-iot.org:8443',
  type: 'system',
  errno: 'ENOTFOUND',
```

It's all the more strange since I haven't actually opened the "get some new addons" page. And in theory the add-ons page shouldn't be phoning home when just opening the installed add-ons page (I remember when that was removed). Odd.

**Comment by mrstegeman** [comment]
That happens when your gateway doesn't have internet connectivity. The gateway tries to auto-update all add-ons daily.

**Comment by flatsiedatsie** [comment]
Ah, that explains it. Odd though. I just tested it, and the gateway does have internet.

**Comment by mrstegeman** [comment]
Internet seems to be pretty flaky on my RPi, even connected via ethernet.

**Comment by flatsiedatsie** [comment]
I'm still noticing the error once in a while, on devices that have internet connectivity. But it doesn't affect functionality.

**Comment by flatsiedatsie** [comment]
```
2019-12-05 14:50:05.420 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7 failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443
    at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1455:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7 failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

**Comment by mrstegeman** [comment]
Same thing here, it's a DNS timeout failure.

**Comment by flatsiedatsie** [comment]
OK. I noticed this in the console too:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7. (Reason: CORS request did not succeed).
```

**Comment by mrstegeman** [comment]
That shouldn't be happening. What browser? Is it reproducible?

**Comment by flatsiedatsie** [comment]
Firefox. And I have seen more of the error, but it's probably user error on my end, not sure yet. 

I think it might have something to do with restarting the Gateway, or with the Privacy Manager missing a CSS file that the manifest.json referred to. I keep seeing an `Unknown extension: privacy-manager` error in the console.log: even though it seems to load ok. That error happens early in the page load, before the `show()` method is even called.

I also notice some "switching protocols" messages in the logs.

```
06:51:34.897 The connection to ws://redacted.local/internal-logs?jwt=eyJhbGciOiJFUzI1NiIsI-netc-Nlcl90b2tlbiIsImlhdCI6MTU3NTI5MzkzOCwiaXNzIjoiTm90IHNldC4ifQ.oMXu0KozFex0cpraqIkL3VqC6o_VbSZAlXp_PU6gXq6TrPl54KZMRL3h_QxxYpebn7Nu1a-MS1pHYTlg4Ow was interrupted while the page was loading. 9ba0b98a02b85688ed96-app.js:24696:25
06:51:34.925 The connection to ws://redacted.local/things?jwt=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImQzNzcyMGFhLTQ0OTktNGNlNy1iYThhLWI5YWJhMmU4NzU5MiJ9.e2etc6o_VZAlXp_PU6gXq6TrPl54KZMRL3h_QxxKiwYpebn7Nu1a-MS1pHYTlg4Ow was interrupted while the page was loading. 9ba0b98a02b85688ed96-app.js:34018:16
07:41:13.269 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.10.0&node=57&python=2.7%2C3.7. (Reason: CORS request did not succeed).

07:41:13.269
TypeError: "NetworkError when attempting to fetch resource."
```

**Comment by flatsiedatsie** [comment]
Ah, as expected, user error. I changed the domain name of the server, and that means a privacy protecting add-on in my browser (uMatrix) was not allowing the connection.

**Comment by mrstegeman** [comment]
Ok, good to know it’s not the gateway! That would e been bad.

**Comment by flatsiedatsie** [comment]
Just randomly saw this again, despite the privacy protections being disabled for the gateway.

``` 
2020-06-11 18:28:32.603 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.12.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org api.mozilla-iot.org:8443
    at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.12.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org api.mozilla-iot.org:8443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

Probably overlooking something on my end.

**Comment by mrstegeman** [comment]
Still a DNS issue...
