### ISSUE TITLE
Fail to build docker image 

### ISSUE THREAD

**Issue by alshaboti** [mozilla-iot/gateway#2482]
I couldn't build Docker image. I use the following commands.
```
git clone https://github.com/mozilla-iot/gateway.git
cd gateway
sudo docker build mozgateway:latest .
```
It fails with the following error. Do you know how to fix that? 

```
< I cut the previous output>
node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/root/mozilla-iot/gateway/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" is installed via remote

> segfault-handler@1.3.0 install /root/mozilla-iot/gateway/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/root/mozilla-iot/gateway/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
In file included from ../src/segfault-handler.cpp:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../../nan/nan.h:54,
                 from ../src/segfault-handler.cpp:2:
../src/segfault-handler.cpp: At global scope:
/root/.cache/node-gyp/10.20.0/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/10.20.0/include/node/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/segfault-handler.cpp:346:3: note: in expansion of macro ‘NODE_MODULE’
   NODE_MODULE(segfault_handler, init)
   ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/10.20.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/segfault-handler.cpp:2:
/root/.cache/node-gyp/10.20.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/10.20.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/10.20.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.20.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/10.20.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory '/root/mozilla-iot/gateway/node_modules/segfault-handler/build'

> fsevents@1.2.12 install /root/mozilla-iot/gateway/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

make: Entering directory '/root/mozilla-iot/gateway/node_modules/chokidar/node_modules/fsevents/build'
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make: Leaving directory '/root/mozilla-iot/gateway/node_modules/chokidar/node_modules/fsevents/build'

> optipng-bin@6.0.0 postinstall /root/mozilla-iot/gateway/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /root/mozilla-iot/gateway/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@5.0.0 postinstall /root/mozilla-iot/gateway/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at Promise.all.then.arr (/root/mozilla-iot/gateway/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@5.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@5.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-19T17_33_00_796Z-debug.log
The command '/bin/sh -c echo "#log: ${project}: Preparing sources"   && set -x   && ./gateway/install.sh' returned a non-zero code: 1

```

**Comment by mrstegeman** [comment]
You’ll probably have better luck building this repo: https://github.com/mozilla-iot/gateway-docker
