### ISSUE TITLE
Network settings are not supported for this platform

### ISSUE THREAD

**Issue by mbecker** [mozilla-iot/gateway#2489]
Hi,

I've cloned the repo on my remote server in the internet (cloud), installed all necessary modules as listed at the front page and started the gateway, I'm able to reach the the gateway at the server's ip:8080 adress.

At the setup screen I entered the subdomain name for the mozilla-iot.org proxy. The UI indicated the requesting process to the Mozilla's server with the spinning icon. In the logs the following error ocurred:
```sh
2020-04-28 22:22:35.066 INFO   : [pagekite] stderr: Traceback (most recent call last):
  File "/home/mbecker/apps/mozilla/gateway/pagekite.py", line 254, in <module>

2020-04-28 22:22:35.069 INFO   : [pagekite] stderr:     exec __FILES[".SELF/sockschain/__init__.py"] in m.__dict__
  File "<string>", line 49, in <module>
ImportError: No module named six

2020-04-28 22:22:35.070 INFO   : [pagekite] process exited with code 1
```

After that I installed te following modules as follows:
```sh
sudo apt install python-pip python3-pip
sudo python3 -m pip install git+https://github.com/mozilla-iot/gateway-addon-python#egg=gateway_addon
```
(This information is only listed at the front page in the section of dev tools)

Then I started the gateway server again:
```sh
[...]
2020-04-28 22:26:10.008 INFO   : Service Discovery: changing profile - local domain is now: Ubuntu-1804-bionic-64-minimal
2020-04-28 22:26:10.010 INFO   : Service Discovery: state changed to: true
2020-04-28 22:26:11.629 INFO   : PageKite connected!
2020-04-28 22:26:11.631 INFO   : Starting certificate renewal.
2020-04-28 22:26:11.641 INFO   : Certificate not yet due for renewal.
2020-04-28 22:26:20.127 INFO   : Checking for add-on updates...
2020-04-28 22:26:20.960 INFO   : Finished updating add-ons
2020-04-28 22:26:57.877 INFO   : Tunnel domain found. Tunnel name is: REALNAME and tunnel domain is: mozilla-iot.org
2020-04-28 22:26:57.878 INFO   : Tunnel name is set to: https://REALNAME.mozilla-iot.org
2020-04-28 22:26:57.878 INFO   : Local mDNS Service Domain Name is: Ubuntu-1804-bionic-64-minimal
2020-04-28 22:27:01.726 INFO   : Opened a new things socket
2020-04-28 22:27:29.604 INFO   : Tunnel domain found. Tunnel name is: REALNAME and tunnel domain is: mozilla-iot.org
2020-04-28 22:27:29.606 INFO   : Tunnel name is set to: https://REALNAME.mozilla-iot.org
2020-04-28 22:27:29.606 INFO   : Local mDNS Service Domain Name is: Ubuntu-1804-bionic-64-minimal

("REALNAME" is my oiginal subdomain name)
```
Interesting is here that the "PageKite" is now working and that the subdomain was registered at Mozilla's proxy service.

Then again I was able to open the browser page at the server's ip:8080 adress and then to enter my user details. The screen with entering the proxy name wasn't shown (I think it's already saved in the config and I'm able to connect via Mozilla proxy).

But I'm neiher able to add new things nor to enter any network settings. The following text is displayed at the network settings
```html
Network settings are not supported for this platform.
```

So my original question besides the hack to install the python pip modules is as follows:

**Can I start the gateway on a remote server in the cloud only connected to the internet via eth?**

My use case is to add web things via URL. I'm using the Mozilla IoT Framework to "create" own things which are connected via MQTT to the hardware devices. That use case is already working on my local rpi with the gateway image in my local network (no problems with the rpi image).

Thanks for your help and maybe I've discovered another issue with the python pip modules.

**Comment by mrstegeman** [comment]
Let me address things one by one.

1. Error with `six` module: this was introduced with an updated PageKite version. I've update the README for this.
2. gateway_addon module: this is already noted in the README, however I added instructions for installing `pip`.
3. Network settings: these are only really supported in our Raspberry Pi builds, specifically for configuring Wi-Fi and/or Ethernet. We used to have more advanced configuration as well when we supported OpenWrt for routers.
4. Adding web things: You'll need to install the "Web Thing" add-on for this to work.

**Comment by mbecker** [comment]
Hi @mrstegeman ,

thank's for adressing these issues. Shame on me! (1) and (2) are noted in the README. I've not read these instructions; especially for (1).

And (4) adresses my issue perfectly. I've forgotten that I installed this addon on my local gateway.

Thank you very much and thanks for the README. Always a good hint to read the instructions in detail :-)
