### ISSUE TITLE
Cannot find module 'gateway-addon'

### ISSUE THREAD

**Issue by rshadow** [mozilla-iot/gateway#2499]
Reproduce:
* Intalled 0.11 from deb. Work good.
* Upgrade from 0.11 to 0.12. Work good.
* Upgrade Chromecast plugin to 0.4.3
* Plugin Yeelight 0.3.1 work good.
* All other plugins disabled with same error: Cannot find module 'gateway-addon'

Log on plugin OpenUV - Clear sky UV index 0.5.1:
```
2020-05-22 14:14:56.807 INFO   : Loading add-on: openuv-adapter
2020-05-22 14:15:01.626 INFO   : openuv-adapter: Opening database: /etc/webthings-gateway/config/db.sqlite3
2020-05-22 14:15:02.123 INFO   : openuv-adapter: Loading add-on openuv-adapter from /etc/webthings-gateway/addons/openuv-adapter
2020-05-22 14:15:02.194 ERROR  : openuv-adapter: { Error: Cannot find module 'gateway-addon'
2020-05-22 14:15:02.195 ERROR  : openuv-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2020-05-22 14:15:02.196 ERROR  : openuv-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2020-05-22 14:15:02.197 ERROR  : openuv-adapter:     at Module.require (internal/modules/cjs/loader.js:637:17)
2020-05-22 14:15:02.197 ERROR  : openuv-adapter:     at require (internal/modules/cjs/helpers.js:22:18)
2020-05-22 14:15:02.198 ERROR  : openuv-adapter:     at Object.<anonymous> (/etc/webthings-gateway/addons/openuv-adapter/openuv-adapter.js:15:5)
2020-05-22 14:15:02.198 ERROR  : openuv-adapter:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2020-05-22 14:15:02.198 ERROR  : openuv-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2020-05-22 14:15:02.199 ERROR  : openuv-adapter:     at Module.load (internal/modules/cjs/loader.js:599:32)
2020-05-22 14:15:02.199 ERROR  : openuv-adapter:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2020-05-22 14:15:02.199 ERROR  : openuv-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```
Chromecast 0.4.3:
```
2020-05-22 14:22:38.421 INFO   : Loading add-on: chromecast-adapter
2020-05-22 14:22:40.759 INFO   : chromecast-adapter: Opening database: /etc/webthings-gateway/config/db.sqlite3
2020-05-22 14:22:41.209 INFO   : chromecast-adapter: Loading add-on chromecast-adapter from /etc/webthings-gateway/addons/chromecast-adapter
2020-05-22 14:22:41.454 ERROR  : chromecast-adapter: { Error: Cannot find module 'gateway-addon'
2020-05-22 14:22:41.455 ERROR  : chromecast-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2020-05-22 14:22:41.455 ERROR  : chromecast-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2020-05-22 14:22:41.456 ERROR  : chromecast-adapter:     at Module.require (internal/modules/cjs/loader.js:637:17)
2020-05-22 14:22:41.457 ERROR  : chromecast-adapter:     at require (internal/modules/cjs/helpers.js:22:18)
2020-05-22 14:22:41.457 ERROR  : chromecast-adapter:     at Object.<anonymous> (/etc/webthings-gateway/addons/chromecast-adapter/adapter.js:13:5)
2020-05-22 14:22:41.458 ERROR  : chromecast-adapter:     at Module._compile (internal/modules/cjs/loader.js:689:30)
2020-05-22 14:22:41.458 ERROR  : chromecast-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2020-05-22 14:22:41.459 ERROR  : chromecast-adapter:     at Module.load (internal/modules/cjs/loader.js:599:32)
2020-05-22 14:22:41.459 ERROR  : chromecast-adapter:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2020-05-22 14:22:41.460 ERROR  : chromecast-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```
and same for other.

Reinstall deb not fix problem.
It seems that deleting the entire configuration may fix the error. But I have not tried it yet.

**Comment by mrstegeman** [comment]
Can you try this:

```
cd /opt/webthings-gateway/node_modules/gateway-addon
sudo npm link
sudo systemctl restart webthings-gateway.service
```

If that still doesn't work, try this:

```
sudo su -
cd /etc/webthings-gateway/addons/openuv-adapter
sudo -u webthings link gateway-addon
exit
sudo systemctl restart webthings-gateway.service
```

**Comment by rshadow** [comment]
```
webthings:[~]$ cd /opt/webthings-gateway/node_modules/gateway-addon
webthings:[/opt/webthings-gateway/node_modules/gateway-addon]$ sudo npm link 
sudo: npm: command not found
```

```
root@webthings:/etc/webthings-gateway/addons/openuv-adapter# sudo -u webthings link gateway-addon
link: missing operand after 'gateway-addon'
Try 'link --help' for more information.
```

**Comment by rshadow** [comment]
I installed npm from stable debian. And I tried to run the commands again. It looks like it worked.

```
webthings:[~]$ cd /opt/webthings-gateway/node_modules/gateway-addon
webthings:[/opt/webthings-gateway/node_modules/gateway-addon]$ sudo npm link
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> sqlite3@4.2.0 install /opt/webthings-gateway/node_modules/gateway-addon/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/opt/webthings-gateway/node_modules/gateway-addon/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" is installed via remote
npm WARN lifecycle gateway-addon@0.12.0~prepare: cannot run in wd gateway-addon@0.12.0 if [ ! -d schema/messages ]; then git submodule init; git submodule update; fi (wd=/opt/webthings-gateway/node_modules/gateway-addon)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 200 packages from 157 contributors in 80.715s
/usr/local/lib/node_modules/gateway-addon -> /opt/webthings-gateway/node_modules/gateway-addon
webthings:[/opt/webthings-gateway/node_modules/gateway-addon]$ sudo systemctl restart webthings-gateway.service
```

**Comment by rshadow** [comment]
Application log:
https://gist.github.com/rshadow/d665823171984db1a7b0c5f75b83bf72

**Comment by mrstegeman** [comment]
Looks like things are working now, correct?

**Comment by rshadow** [comment]
> Looks like things are working now, correct?
yes
