### ISSUE TITLE
If I start the gateway using the -p option, it ignores it and uses the config anyways

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#251]
```
810 >npm start -- -p 8888

> things-gateway@0.1.0 start /home/dhylands/Dropbox/moziot/gateway
> webpack && node build/gateway.js "-p" "8888"
...snip...
Listening on port 8888
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at startHttpsGateway (/home/dhylands/Dropbox/moziot/gateway/build/webpack:/src/app.js:58:1)
    at Object.<anonymous> (/home/dhylands/Dropbox/moziot/gateway/build/webpack:/src/app.js:172:1)
    at __webpack_require__ (/home/dhylands/Dropbox/moziot/gateway/build/webpack:/webpack/bootstrap 1ec42aea80a235bdee05:19:1)
    at /home/dhylands/Dropbox/moziot/gateway/build/webpack:/webpack/bootstrap 1ec42aea80a235bdee05:62:1
    at Object.<anonymous> (/home/dhylands/Dropbox/moziot/gateway/build/gateway.js:67:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```
In particular, the startHttpGateway function seems to be doing the right thing:
https://github.com/mozilla-iot/gateway/blob/465096a1e0333d64641005cfc3c23d40861be76a/src/app.js#L66-L70

but the redirector doesn't:
https://github.com/mozilla-iot/gateway/blob/465096a1e0333d64641005cfc3c23d40861be76a/src/app.js#L55-L58

My machine happens to have another service already using port 8080 which is how I ran into this.

**Comment by hobinjk** [comment]
The problem is that there's only one `-p` flag but there are two ports that can be configured when there's an HTTP redirector.

I'm not sure what solution would be best here but we could introduce some subset of `--httpPort`, `--httpsPort`, or `--no-redirector`

**Comment by dhylands** [comment]
As long as both http and https can be configured using a config file, then I'm all for removing the -p option altogether (and perhaps look at removing some of the other options as well). The -p option was created long before we had config files.

**Comment by benfrancis** [comment]
@dhylands Did this ever get changed?

**Comment by dhylands** [comment]
It looks like you can configure the http and https ports via config (ports.http and ports.https) .

It looks like -p is still supported, and used for both the http and https port number (which seems less than useful).

I can remove the -p option if you'd like.

**Comment by benfrancis** [comment]
@dhylands I was just trying to close some old bugs. But yes, setting the same port for http and https doesn't sound particularly helpful :)
