### ISSUE TITLE
After few commands, the Zigbee adapter becomes unresponsive 

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#299]

**Comment by andrenatal** [comment]
<img width="569" alt="screenshot 2017-09-26 17 09 14" src="https://user-images.githubusercontent.com/973388/30889795-ad5bca86-a2dd-11e7-895c-cc58c1f4faba.png">

**Comment by dhylands** [comment]
It would be good to get some log files when this happens.

**Comment by andrenatal** [comment]
```

getValue for property on for: zwave-da95d8e6-5-Switch returning false
getValue for property on for: zb-0022a300001af3b7-onOffSwitch returning false

Unhandled Rejection
ZigBee: setProperty property on already has a set in progress.
```

**Comment by andrenatal** [comment]
more logs:

```
Transmit Status ERROR: 0x26
Unhandled Rejection
{ Error
    at ClientRequest.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketOnEnd (_http_client.js:394:9)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to https://127.0.0.1:4443/things/zb-0022a300001af3b7/properties/on failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

**Comment by DavidKarlas** [comment]
What you probably want to do is turn all this debug flags to true and reproduce, that will give much more data about what is happening in communication with zigbee device...
https://github.com/mozilla-iot/gateway/blob/master/src/adapters/zigbee/zb-adapter.js#L86-L105

**Comment by dhylands** [comment]
I created PR #331 which I believe addresses this issue. Closing for now.
