### ISSUE TITLE
OpenZwave symbol not found but included anyway 

### ISSUE THREAD

**Issue by artynet** [mozilla-iot/gateway#342]
Hello folks, I'm trying to run the platform on the LEDE distro running on my RaspberryPi 3. All the build process is smooth from the library installation to the **yarn** build but when launching :

```
root@rpi3-lede /root/mozilla-iot-gateway [#]# node -v
v8.7.0
root@rpi3-lede /root/mozilla-iot-gateway [#]# npm -v
5.5.1
root@rpi3-lede /root/mozilla-iot-gateway [#]#
npm start
```

I get this error :

```
WARNING in ./src/adapter-manager.js
27:9-16 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Opening database: ./db.sqlite3
Not loading adapters for gpio - disabled
Loading adapters for zigbee from ./adapters/zigbee
Loading adapters for zwave from ./adapters/zwave
initialising OpenZWave addon (/root/mozilla-iot-gateway/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node)
Error: Error relocating /root/mozilla-iot-gateway/node_modules/openzwave-shared/build/Release/openzwave_shared.node: _ZN9OpenZWave7Manager13GetValueUnitsERKNS_7ValueIDE: symbol not found
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/mozilla-iot-gateway/node_modules/openzwave-shared/lib/openzwave-shared.js:26:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/mozilla-iot-gateway/build/adapters/zwave/zwave-adapter.js:16:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! things-gateway@0.2.0 start: `webpack && node build/gateway.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the things-gateway@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-19T16_28_45_998Z-debug.log
```
I have run a `grep` of the **.node** bytecode and the symbol is residing inside as it should. The same applies to the shared library, what am I missing ? Also exporting `LD_LIBRARY_PATH` is not helping....any hints ?

Best, Arturo

**Comment by dhylands** [comment]
When building for ubuntu, I've normally just had to do:
```
sudo ldconfig
```
after doing the `sudo make install` to install the open-zwave library. Do you have a link to the LEDE distro that you're using?

**Comment by artynet** [comment]
Hello @dhylands,

sorry to get back to you so late but I have finally figured out the issue ! When packaging the libraries I have to omit the final **STRIP** compression step, in the **OpenWRT/LEDE SDK**, otherwise all the library symbols will be lost. Once removed, the server is running smoothly from scratch (i.e. generation of the security certificate).

I have also cross-compiled the required node modules  leveraging the bash script in the root folder of the sources. The same principle applies when using as **SYSROOT** the folder of the given **OpenWRT/LEDE SDK** instead of custom path where installing the cross-built libraries.

I think the porting should be considered complete....thank you again for your support.

Best, Arturo
