### ISSUE TITLE
Intermittent WS Test Failure

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#361]
From travis:
```
● things/ › should receive event notifications over websocket

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      

      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)

      at ontimeout (timers.js:386:14)

      at tryOnTimeout (timers.js:250:5)

      at Timer.listOnTimeout (timers.js:214:5)

  ● things/ › should receive thing's action status messages over websocket

    expect(received).toEqual(expected)

    

    Expected value to equal:

      "event"

    Received:

      "propertyStatus"

      

      at it (src/test/integration/things-test.js:663:37)

      at process._tickCallback (internal/process/next_tick.js:109:7)

error:   new API Error: Invalid rule: Unsupported or invalid trigger type:Whatever

(node:10877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'replace' of null

(node:10877) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

error:   new API Error: Engine failed to get rule: Rule 1337 does not exist

(node:10877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'replace' of null

warn:    Property.stop was not started

warn:    Property.stop was not started

error:   new API Error: Engine failed to delete rule: Rule 0 already does not exist

error:   new API Error: Engine failed to update rule: Rule 0 does not exist

(node:10877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): TypeError: Cannot read property 'replace' of null

(node:10877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): TypeError: Cannot read property 'replace' of null

(node:10877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'replace' of null

warn:    Property.stop was not started

 FAIL  src/test/rules-engine/index-test.js (10.992s)

  ● Console
```

**Comment by hobinjk** [comment]
(part about rules is almost definitely unrelated, but we'll see)

**Comment by dhylands** [comment]
I ran into this alot while testing adapter IPC. In that case it was caused by the adapter IPC using named pipes (which are stored on the filesystem) and having multiple tests running in parallel trying to use the same named pipe. I haven't seen it since I switched the adapter IPC to use inproc during testing. But there might be something else causing a similar behaviour.

**Comment by hobinjk** [comment]
Another failure:
[log.txt](https://github.com/mozilla-iot/gateway/files/1492132/log.txt)
