### ISSUE TITLE
Divergence between the sqlite binding version installed by npm and the one asked by the app

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#50]
When installing the gateway on Rpi, npm installs the sqlite version 51 and the app wants to run version 46. Symlinking them seems to work, but we need to figure why the divergence occurs.
 
```

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)

```

```
pi@vaani:~/wot/gateway $ sudo node app.js
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pi/wot/gateway/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/wot/gateway/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
pi@vaani:~/wot/gateway $ ls
adapter.js          adapters  controllers  db.sqlite3   device.js  models        package.json  static    utils.js
adapter-manager.js  app.js    db.js        deferred.js  LICENSE    node_modules  README.md     thing.py
pi@vaani:~/wot/gateway $ ls /home/pi/wot/gateway/node_modules/sqlite3/lib/binding/node-v46-linux-arm/
ls: cannot access /home/pi/wot/gateway/node_modules/sqlite3/lib/binding/node-v46-linux-arm/: No such file or directory
pi@vaani:~/wot/gateway $ ls /home/pi/wot/gateway/node_modules/sqlite3/lib/binding/
node-v51-linux-arm
```

**Comment by mrstegeman** [comment]
Closing this unless we see it again.
