### ISSUE TITLE
Philips Hue Bridge not being detected

### ISSUE THREAD

**Issue by BlackHoleFox** [mozilla-iot/gateway#686]
When trying to pair a Philips Hue Bridge and it's devices to the Things Gateway, none of the devices show up. I have verified that the bridge is functional still and I can access its internal API at a static local IP address. When pinging said local IP on the machine running the Gateway, it gets a response back, and a traceroute shows no problems. I have tried every variation of pressing the button on the bridge and enabling/disabling the Philips Hue addon. Anyone have any ideas or is this a bug with the addon?

**Comment by hobinjk** [comment]
That's really weird. There's nothing obviously wrong that I can think of. Could you share the contents of your gateway's log? If running on a raspberry pi this is output at `~/mozilla-iot/gateway/run-app.log`.
To make sure that the log contains the relevant information make sure the Philips Hue add-on is enabled then
1. Click the "+" icon on the main page of the Gateway
2. Press the link button on the hue bridge

**Comment by BlackHoleFox** [comment]
@hobinjk Its running in a Ubuntu Enviroment, and I couldn't find anything in the log folder but here is the terminal output. Did exactly as you said with the bridge and still no good. Can confirm aswell that the bridge is functional and still responding to pings.
```2018-02-20 15:36:48.580 Opening database: ./db.sqlite3
2018-02-20 15:36:48.784 Listening on port 4443
2018-02-20 15:36:48.798 Redirector listening on port 8080
2018-02-20 15:36:48.943 Loading add-on: philips-hue-adapter
2018-02-20 15:36:48.976 Loading add-on: zigbee-adapter
2018-02-20 15:36:48.996 Loading add-on: zwave-adapter
2018-02-20 15:36:49.475 philips-hue: Opening database: ./db.sqlite3
2018-02-20 15:36:49.490 philips-hue: Loading add-on for philips-hue-adapter from /home/iotadmin/gateway/build/addons/philips-hue-adapter
2018-02-20 15:36:49.492 zigbee: Opening database: ./db.sqlite3
2018-02-20 15:36:49.496 zwave: Opening database: ./db.sqlite3
2018-02-20 15:36:49.508 zigbee: Loading add-on for zigbee-adapter from /home/iotadmin/gateway/build/addons/zigbee-adapter
2018-02-20 15:36:49.513 zwave: Loading add-on for zwave-adapter from /home/iotadmin/gateway/build/addons/zwave-adapter
2018-02-20 15:36:49.554 zwave: initialising OpenZWave addon (/home/iotadmin/gateway/node_modules/openzwave-shared/lib/../build/Release/openzwave_shared.node)
2018-02-20 15:36:49.555 zwave: Failed to load zwave-adapter - Failed to load openzwave-shared: Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory
2018-02-20 15:36:49.562 Plugin: zwave-adapter died, code = 100 NOT restarting...
2018-02-20 15:36:49.805 zigbee: Failed to load zigbee-adapter - No Digi port found
2018-02-20 15:36:49.809 Plugin: zigbee-adapter died, code = 100 NOT restarting...
2018-02-20 15:36:50.101 philips-hue: no known bridges
2018-02-20 15:37:06.310 Opened a new things socket
2018-02-20 15:38:06.295 Pairing timeout
2018-02-20 15:38:06.297 Thing was not added
2018-02-20 15:38:06.297 addNewThing cancelled```

**Comment by hobinjk** [comment]
Thanks for the info! Sorry that this is behaving so strangely. Can you see your bridge listed in https://www.meethue.com/api/nupnp ?

**Comment by BlackHoleFox** [comment]
@hobinjk Yep, shows up there and the internal API is at full functionality as well.

**Comment by hobinjk** [comment]
Okay, so if you can see the bridge on that link then when you clicked the "+" button on the main page the Gateway should have started logging
```
2018-02-20 19:13:02.818 philips-hue: { type: 101,
2018-02-20 19:13:02.818 philips-hue:   address: '',
2018-02-20 19:13:02.818 philips-hue:   description: 'link button not pressed' }
```
over and over until you pressed the hub's link button or canceled pairing by pressing the back button.

Just to make sure we're on the same page, I've made a diagram of the process I'm following to get to this state:
![diagram](https://user-images.githubusercontent.com/2776089/36456579-8bca8772-1673-11e8-8e6f-42bbe7ae28af.png)

**Comment by BlackHoleFox** [comment]
@hobinjk Followed the exact steps and this is what appears. It spins for several seconds and then shows this.
![capture](https://user-images.githubusercontent.com/20936452/36456905-43988edc-169f-11e8-8115-40914ecb4918.PNG)

**Comment by hobinjk** [comment]
Sorry for the delay in responding! This problem is really insidious.

First, if the adapter can see a bridge it should be listed under https://localhost:4443/settings/adapters. If it isn't present there, either the add-on at https://localhost:4443/settings/addons is disabled or there's something happening to break the discovery.

If there's something messing with the discovery I've attached a tarball with an alternative version of the Philips Hue adapter with some debugging of the discovery process. If you replace the contents of the `build/addons/philips-hue-adapter` directory with the contents of this archive there should be enough information in the Gateway's output for me to learn more about what's going on.

[philips-hue-adapter.tar.gz](https://github.com/mozilla-iot/gateway/files/1752260/philips-hue-adapter.tar.gz)

**Comment by BlackHoleFox** [comment]
@hobinjk As stupid as this is going to sound, after installing updates for my Ubuntu Dist that came through only today, it detected the bridge and successfully linked after console spam of "button not pressed" until I pressed it. I am not sure what exactly caused this. I did the exact same thing I did originally and it just found the bridge. Do you think a package update from `apt` fixed something?

**Comment by hobinjk** [comment]
@BlackHoleFox Huh, that is really weird but I'm glad it's working! I have no idea what could have happened.

**Comment by SketchThis** [comment]
I'm having the same issue as described here. My Hue Bridge is up and running, and I'm able to use it with several other devices. 

I'm able to see it's IP address with the link above. This is what I'm seeing in the logs:

02-16 22:50:48.263 ERROR  : philips-hue: Error updating devices TypeError: Cannot read property 'hasOwnProperty' of undefined
2019-02-16 22:50:48.264 ERROR  : philips-hue:     at new PhilipsHueDevice (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:337:23)
2019-02-16 22:50:48.267 ERROR  : philips-hue:     at PhilipsHueAdapter.updateDevice (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:752:5)
2019-02-16 22:50:48.268 ERROR  : philips-hue:     at Promise.all.then.then (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:706:14)
2019-02-16 22:50:48.270 ERROR  : philips-hue:     at <anonymous>
2019-02-16 22:50:48.272 ERROR  : philips-hue:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-02-16 22:50:49.598 ERROR  : philips-hue: Error updating devices TypeError: Cannot read property 'hasOwnProperty' of undefined
2019-02-16 22:50:49.599 ERROR  : philips-hue:     at new PhilipsHueDevice (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:337:23)
2019-02-16 22:50:49.600 ERROR  : philips-hue:     at PhilipsHueAdapter.updateDevice (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:752:5)
2019-02-16 22:50:49.602 ERROR  : philips-hue:     at Promise.all.then.then (/home/pi/.mozilla-iot/addons/philips-hue-adapter/philips-hue-adapter.js:706:14)
2019-02-16 22:50:49.603 ERROR  : philips-hue:     at <anonymous>

I'm running on a Raspberry Pi 3...

**Comment by mrstegeman** [comment]
@SketchThis I opened https://github.com/mozilla-iot/philips-hue-adapter/issues/38 for you.
