### ISSUE TITLE
Error when starting Gateway due to migration expecting ~/.mozilla-iot/addons/adapter.js to exist

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#728]
```
Error: ENOENT: no such file or directory, lstat '/Users/jhobin/.mozilla-iot/addons/adapter.js'
    at Object.fs.lstatSync (fs.js:961:11)
    at Object.migrate (/Users/jhobin/moziot/gateway/build/webpack:/src/user-profile.js:181:1)
    at Object.<anonymous> (/Users/jhobin/moziot/gateway/build/webpack:/src/app.js:14:1)
    at __webpack_require__ (/Users/jhobin/moziot/gateway/build/webpack:/webpack/bootstrap 454c6cccfa511fb7277c:19:1)
    at /Users/jhobin/moziot/gateway/build/webpack:/webpack/bootstrap 454c6cccfa511fb7277c:62:1
    at Object.<anonymous> (/Users/jhobin/moziot/gateway/build/gateway.js:67:10)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Comment by hobinjk** [comment]
Will be closed by #726
