### ISSUE TITLE
cant run the gateway

### ISSUE THREAD

**Issue by YuvalHir** [mozilla-iot/gateway#982]
hey,
im trying to run the gateway but i get an error, this is my log:
windows 10 64bit
node version: v8.9.4
npm version: 5.6.0
```
Opening database: C:\Users\Yuval\.mozilla-iot\config\db.sqlite3
2018-05-04 12:33:23.819 Listening on port 8080
2018-05-04 12:33:23.898 Unhandled Rejection
2018-05-04 12:33:23.899 { Error: Could not locate the bindings file. Tried:
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\build\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\build\Debug\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\build\Release\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\out\Debug\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\Debug\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\out\Release\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\Release\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\build\default\node_nanomsg.node
 → C:\users\yuval\documents\gateway\node_modules\nanomsg\compiled\8.9.4\win32\x64\node_nanomsg.node
    at bindings (C:\users\yuval\documents\gateway\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\users\yuval\documents\gateway\node_modules\nanomsg\lib\index.js:1:40)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.nanomsg (C:\users\yuval\documents\gateway\build\webpack:\external "nanomsg":1:1)
    at __webpack_require__ (C:\users\yuval\documents\gateway\build\webpack:\webpack\bootstrap:22:1)
    at Object../src/plugin/ipc.js (C:\users\yuval\documents\gateway\build\webpack:\src\plugin\ipc.js:5:1)
    at __webpack_require__ (C:\users\yuval\documents\gateway\build\webpack:\webpack\bootstrap:22:1)
    at Object../src/plugin/plugin-client.js (C:\users\yuval\documents\gateway\build\webpack:\src\plugin\plugin-client.js:18:1)
    at __webpack_require__ (C:\users\yuval\documents\gateway\build\webpack:\webpack\bootstrap:22:1)
    at AddonManager.loadAddons (C:\users\yuval\documents\gateway\build\webpack:\src\addon-manager.js:643:1)
  tries:
   [ 'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\build\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\build\\Debug\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\build\\Release\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\out\\Debug\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\Debug\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\out\\Release\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\Release\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\build\\default\\node_nanomsg.node',
     'C:\\users\\yuval\\documents\\gateway\\node_modules\\nanomsg\\compiled\\8.9.4\\win32\\x64\\node_nanomsg.node' ] }
```

**Comment by mrstegeman** [comment]
It looks like you may have failed to install `nanomsg`. The following additional steps are required on Windows:

### Install OpenSSL (Windows only)

The Gateway depends on [`ursa`](https://github.com/JoshKaufman/ursa), which requires OpenSSL.

Install [OpenSSL](http://slproweb.com/products/Win32OpenSSL.html) =< 1.0.2 (normal, not light) in the same bitness as your Node.js.

[See here](https://github.com/JoshKaufman/ursa#windows-install).

### Install Python 2.7 (Windows only)

PageKite works with Python 2.7.

Install Python 2.7 from [here](https://www.python.org/downloads/windows/).

Enable "register extensions" on installing package, or associate file extension `.py` with python.

### Install Python 3.X and packages (Optional, Windows only)

This is required in order to use Python 3 add-ons, e.g. [tplink-adapter](https://github.com/mozilla-iot/tplink-adapter/).

* Install Python 3.X (ideally 3.4+) from [here](https://www.python.org/downloads/windows/).
  * Enable "Install launcher for all users" and "Add Python 3.X to PATH" on installing.
  * Enable `python3` command using the following.
```
mklink "C:\path\to\python3\python3.exe" "C:\path\to\python3\python.exe"
```
* Install nanomsg.
  * Follow the directions from [nanomsg](https://github.com/nanomsg/nanomsg) to install in the same bitness as your Python 3.X.
  * If you want to build for 64-bit, you need to execute cmake with `-DCMAKE_GENERATOR_PLATFORM=x64`.
  * Add `C:\path\to\nanomsg\bin` to `PATH`.
* Install nnpy
```
git clone https://github.com/nanomsg/nnpy.git
cd nnpy
```
Add a file: site.cfg
```
[DEFAULT]
include_dirs = C:\path\to\nanomsg\include\nanomsg
library_dirs = C:\path\to\nanomsg\lib
host_library = C:\path\to\nanomsg\bin\nanomsg.dll
```
Execute the following command as an administrator.
```
python3 -m pip install .
python3 -m pip install git+https://github.com/mozilla-iot/gateway-addon-python.git
```

**Note:** 2018-04-12: `pip3` has an [issue](https://github.com/pypa/pip/issues/4251) with some languages.

After doing all of these things, try running `yarn` and `npm start` again.

**Comment by hyuval1511** [comment]
now i got this error:
```
    ERROR in [at-loader] ./global.d.ts:6:8
        TS2300: Duplicate identifier 'EncoderInputTypes'.

    ERROR in [at-loader] ./global.d.ts:8:8
        TS2300: Duplicate identifier 'EncoderInput'.

    ERROR in [at-loader] ./global.d.ts:12:8
        TS2300: Duplicate identifier 'PemParams'.

    ERROR in [at-loader] ./global.d.ts:16:9
        TS2300: Duplicate identifier 'Builder'.

    ERROR in [at-loader] ./global.d.ts:28:9
        TS2300: Duplicate identifier 'Encoder'.

    ERROR in [at-loader] ./global.d.ts:39:12
        TS2300: Duplicate identifier 'ANSN1'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:6:8
        TS2300: Duplicate identifier 'EncoderInputTypes'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:8:8
        TS2300: Duplicate identifier 'EncoderInput'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:12:8
        TS2300: Duplicate identifier 'PemParams'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:16:9
        TS2300: Duplicate identifier 'Builder'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:28:9
        TS2300: Duplicate identifier 'Encoder'.

    ERROR in [at-loader] ./mozilla-iot/gateway/global.d.ts:39:12
        TS2300: Duplicate identifier 'ANSN1'.
```

**Comment by mrstegeman** [comment]
Closing, please re-open if this is still an issue.
